spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:4407/testMyBatisPlus?useUnicode=true&characterEncoding=utf8

mybatis-plus:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    # 打印 sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl